out_dir: results_attribution_gps
metric_best: accuracy
metric_agg: argmax
wandb:
  use: False  # Disable for initial testing

dataset:
  format: attribution_graphs
  name: prompt_injection
  dir: ../data_small  # Path to our dataset
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False

train:
  mode: custom
  batch_size: 8  # Small batch size due to large graphs
  eval_period: 1
  ckpt_period: 10

model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add

gt:
  layer_type: GINE+Transformer  # GINE local MPNN + Transformer global attention
  layers: 4
  n_heads: 4
  dim_hidden: 128
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True

gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 128  # Must match gt.dim_hidden
  batchnorm: True
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False

optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-4
  base_lr: 0.001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10